"""empty message

Revision ID: d55d8e869703
Revises: 
Create Date: 2024-01-09 09:31:55.004991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55d8e869703'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('HotelId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('HotelName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('HotelId'),
    sa.UniqueConstraint('HotelName')
    )
    op.create_table('location_types',
    sa.Column('LocationTypeId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LocationTypeName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('LocationTypeId'),
    sa.UniqueConstraint('LocationTypeId'),
    sa.UniqueConstraint('LocationTypeName')
    )
    op.create_table('order_status',
    sa.Column('OrderStatusId', sa.Integer(), nullable=False),
    sa.Column('StatusName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('OrderStatusId'),
    sa.UniqueConstraint('StatusName')
    )
    op.create_table('order_types',
    sa.Column('OrderTypeId', sa.Integer(), nullable=False),
    sa.Column('OrderTypeName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('OrderTypeId'),
    sa.UniqueConstraint('OrderTypeName')
    )
    op.create_table('users',
    sa.Column('UserId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.Column('FullName', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Password'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('locations',
    sa.Column('LocationId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LocationTypeId', sa.Integer(), nullable=False),
    sa.Column('LocationName', sa.String(), nullable=False),
    sa.Column('Floor', sa.Integer(), nullable=False),
    sa.Column('HotelId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['HotelId'], ['hotels.HotelId'], name='fk_location_hotel', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['LocationTypeId'], ['location_types.LocationTypeId'], name='fk_location_type', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('LocationId'),
    sa.UniqueConstraint('LocationId')
    )
    op.create_table('user_hotel_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.HotelId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.UserId'], )
    )
    op.create_table('orders',
    sa.Column('OrderId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LocationId', sa.Integer(), nullable=True),
    sa.Column('CreationDate', sa.DateTime(), nullable=True),
    sa.Column('EndDate', sa.DateTime(), nullable=True),
    sa.Column('OrderTypeId', sa.Integer(), nullable=True),
    sa.Column('ImageData', sa.String(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('OrderStatusId', sa.Integer(), nullable=True),
    sa.Column('HotelId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['HotelId'], ['hotels.HotelId'], name='fk_location_hotel', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['LocationId'], ['locations.LocationId'], name='fk_location', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['OrderStatusId'], ['order_status.OrderStatusId'], name='fk_orderstatus', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['OrderTypeId'], ['order_types.OrderTypeId'], name='fk_ordertype', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], name='fk_orderType', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('OrderId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('user_hotel_association')
    op.drop_table('locations')
    op.drop_table('users')
    op.drop_table('order_types')
    op.drop_table('order_status')
    op.drop_table('location_types')
    op.drop_table('hotels')
    # ### end Alembic commands ###
